### ISSUE TITLE
TextField's custom error message prop doesn't work

### ISSUE THREAD

**Issue by Magneticmagnum** [DigitalRiver/react-atlas#437] opened 2017-10-29 17:25 UTC
![image](https://user-images.githubusercontent.com/1256043/32146360-411b29bc-bca4-11e7-8c16-f28855b607aa.png)

**Comment by hbowden** [comment] 2017-10-30 16:31
Duplicate of this issue: https://github.com/DigitalRiver/react-atlas/issues/332

**Closed by hbowden** 2017-10-30 16:31 UTC
Labels: bug, duplicate
